version: "3"
services:
  imgo:
    build:
      context: .
    image: imgo:latest
    ports:
      - "80:8090"
    volumes:
      - ${PWD}/config.toml:/app/config.toml
  redis:
    restart: always
    container_name: imgo_redis
    image: redis:7.2
    ports:
      - 6379:6379
    volumes:
      - ${PWD}/redis/data:/data
  rabbit:
    image: rabbitmq:3.12.12-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
